# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' parse parameters in joint model
#' @param filename path to binary file from joint command
#' @export
parse_joint_par <- function(filename) {
    .Call(`_phaseless_parse_joint_par`, filename)
}

#' parse posterior probabilty in joint model
#' @param filename path to binary file from joint command
#' @param chunk which chunk to extract
#' @export
parse_joint_post <- function(filename, chunk = 0L) {
    .Call(`_phaseless_parse_joint_post`, filename, chunk)
}

