# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' parse parameters in joint model
#' @param filename path to binary file from joint command
#' @export
parse_joint <- function(filename) {
    .Call(`_phaseless_parse_joint`, filename)
}

