
name: Linux

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-suggests --no-install-recommends \
                     ca-certificates clang git autoconf automake make zlib1g-dev  \
                     libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev        \
                     libdeflate-dev libncurses5-dev

    - name: build
      run: |
        make -j10

    - name: test
      run: |
        cd tests
        make -j10
        make test
