name: MacOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install dependency
      run: |
        brew install htslib

    - name: build
      run: |
        make -j4

    - name: test
      run: |
        cd tests
        make -j4
        make test
